### ISSUE TITLE
Feature Request: Return MX HA state to 'getnetworkdetail'

### ISSUE THREAD

**Issue by nckrse** [meraki/dashboard-api-python#1]
I am able to pull MX devices for each given network but none of the network API calls return the MX appliance HA status ('Current Master', 'Passive;ready', etc.)

Are there any plans of adding this or any other ways to pull this information via the API? It would be very useful information.

Networks where the MX does not have a warm spare, the status could simply be Null or "Standalone"

**Comment by shiyuechengineer** [comment]
Closing this issue, as it is a feature request that Engineering would need to build. In almost cases, if both of your MXs were up/online, then the primary (add a label to the name for readability) would of course be the current, active master.

**Comment by nckrse** [comment]
Thanks @shiyuechengineer,

I needed this to identify networks in which the MX pair went into master/master but Meraki team has since resolved this bug.
