### ISSUE TITLE
Missing information/doc on rate-limiting

### ISSUE THREAD

**Issue by ksquarekumar** [meraki/dashboard-api-python#100]
In the readme.md there is a link that points to:
https://developer.cisco.com/docs/meraki-api-v1/#!rate-limit does not exist,

this doc does not exist.

**Comment by shiyuechengineer** [comment]
Thanks, this got moved to `https://developer.cisco.com/meraki/api-v1/#!rate-limit` and will be fixed in the repo next week.

**Comment by shiyuechengineer** [comment]
fixed now
