### ISSUE TITLE
Issues with organization.getOrganizations()

### ISSUE THREAD

**Issue by RtKelleher** [meraki/dashboard-api-python#101]
For whatever reason I'm not smart enough to understand why this is failing.

`
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meraki
>>> dashboard = meraki.DashboardAPI(
...         api_key='$API_KEY',
...         base_url='https://api-mp.meraki.com/api/v0/',
...         output_log=True,
...         log_path='',
...         print_console=True
...     )
      meraki:     INFO > Meraki dashboard API session initialized with these parameters: {'self': <meraki.rest_session.RestSession object at 0x7ff8365609a0>, 'logger': <Logger meraki (DEBUG)>, 'api_key': '************************************_KEY', 'base_url': 'https://api-mp.meraki.com/api/v0/', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 60, 'action_batch_retry_wait_time': 60, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 2, 'simulate': False, 'be_geo_id': None, 'caller': None, '__class__': <class 'meraki.rest_session.RestSession'>}

>>> organizations = dashboard.organizations.getOrganizations()
      meraki:     INFO > Organizations, getOrganizations - 200 OK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/meraki/api/organizations.py", line 19, in getOrganizations
    return self._session.get(metadata, resource)
  File "/usr/local/lib/python3.8/dist-packages/meraki/rest_session.py", line 261, in get
    response = self.request(metadata, 'GET', url, params=params)
  File "/usr/local/lib/python3.8/dist-packages/meraki/rest_session.py", line 189, in request
    response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
`

My key is valid, and set as an environmental variable per documentation; which I validated as working through PostMan. However when it comes to the JSONDecodeError I'm functionally not all there.
![Screen Shot 2020-06-25 at 10 58 18 AM](https://user-images.githubusercontent.com/5748165/85744474-ed5e7780-b6d2-11ea-888a-0fa7bb979256.png)

**Comment by shiyuechengineer** [comment]
Hi Ryan, there's an issue currently with the beta mega-proxy, so change that base URL to `https://api.meraki.com/api/v0` to proceed here.

**Comment by shiyuechengineer** [comment]
Looks like it's been fixed, so try again now and see if you still see the issue?

**Comment by picnicsecurity** [comment]
This does not appear to be fixed but it appears to be a typo in the rest_session.py file

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/adam.littrell/PycharmProjects/MerakiAPIToolBox/debugger.py", line 495, in <module>
    organizations = dashboard.organizations.getOrganizations()
AttributeError: 'NoneType' object has no attribute 'organizations'
```
Doing it manually 
```
import meraki as mer 
dashboard = mer.DashboardAPI(api_key='************************************',
...                                      base_url='https://api.meraki.com/api/v0',
...                                      print_console=True,
...                                      maximum_retries=3)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\adam.littrell\PycharmProjects\MerakiAPIToolBox\venv\lib\site-packages\meraki\__init__.py", line 96, in __init__
    self._session = RestSession(
  File "C:\Users\adam.littrell\PycharmProjects\MerakiAPIToolBox\venv\lib\site-packages\meraki\rest_session.py", line 80, in __init__
    sefl._version = __version__
NameError: name 'sefl' is not defined
```

Look at that file I see the following 
```
        # Initialize attributes and properties
        sefl._version = __version__
        self._api_key = str(api_key)
        self._base_url = str(base_url)
        self._single_request_timeout = single_request_timeout
        self._certificate_path = certificate_path
        self._requests_proxy = requests_proxy
```
Changing that to `self` generates a new error.

```
import meraki as mer 
dashboard = mer.DashboardAPI(api_key='************************************',
...                                      base_url='https://api.meraki.com/api/v0',
...                                      print_console=True,
...                                      maximum_retries=3)
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\pydevconsole.py", line 305, in do_exit
    import java.lang.System
  File "C:\Program Files (x86)\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'java'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\adam.littrell\PycharmProjects\merakistuff\venv\lib\site-packages\meraki\__init__.py", line 96, in __init__
    self._session = RestSession(
  File "C:\Users\adam.littrell\PycharmProjects\merakistuff\venv\lib\site-packages\meraki\rest_session.py", line 102, in __init__
    sys.exit(f'If you want to use the Python library with v0 paths ({self._base_url} was configured as the base'
  File "C:\Program Files (x86)\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\pydevconsole.py", line 310, in do_exit
    os._exit(args[0])
TypeError: an integer is required (got type str)

```
Taking away the base URL change allows it to then work
```
dashboard = mer.DashboardAPI(api_key='************************************',
...                                      print_console=True,
...                                      maximum_retries=3)
      meraki:     INFO > Meraki dashboard API session initialized with these parameters: {'self': <meraki.rest_session.RestSession object at 0x000001FF5D8D8910>, 'logger': <Logger meraki (DEBUG)>, 'api_key': '************************************', 'base_url': 'https://api.meraki.com/api/v1', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 60, 'action_batch_retry_wait_time': 60, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 3, 'simulate': False, 'be_geo_id': None, 'caller': None, '__class__': <class 'meraki.rest_session.RestSession'>}
      meraki:     INFO > Meraki dashboard API session initialized with these parameters: {'self': <meraki.rest_session.RestSession object at 0x000001FF5D8D8910>, 'logger': <Logger meraki (DEBUG)>, 'api_key': '************************************2a69', 'base_url': 'https://api.meraki.com/api/v1', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 60, 'action_batch_retry_wait_time': 60, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 3, 'simulate': False, 'be_geo_id': None, 'caller': None, '__class__': <class 'meraki.rest_session.RestSession'>}
organizations = dashboard.organizations.getOrganizations()
      meraki:     INFO > organizations, getOrganizations - 200 OK
      meraki:     INFO > organizations, getOrganizations - 200 OK
```

**Comment by shiyuechengineer** [comment]
Thanks for capturing all these details/logs! Yes, there was a typo there unfortunately in 1.0.0b10 there with `sefl` and will be fixed tomorrow in 1.0.0b11.

As for the second error, because you have version 1.0.0b10, you need to use dashboard API v1, so a `base_url='https://api.meraki.com/api/v1` at a minimum, and not the current `v0` there.

**Comment by picnicsecurity** [comment]
Happy to help. I only just today switched up to the pre-release versions.  Loving it so far.  Just need to adjust some of my api calls in my scripts ( ex dashboard.switch_ports.getDeviceSwitchPorts -> dashboard.switch.getDeviceSwitchPorts )

**Comment by shiyuechengineer** [comment]
Thanks! Yes, that's expected due to the [changes in paths/scopes](https://developer.cisco.com/meraki/api-v1/#!introduction/whats-new-in-v1) between v0 and v1. Appreciate the feedback, Adam!

**Comment by shiyuechengineer** [comment]
release 1.0.0b11 fixed the typo, so closing the issue.
