### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by kustomservices** [meraki/dashboard-api-python#102]
Where can I get documentation on the Python API? For instance, if I want to pull all the MXPortForwardingRules, what "object" is the code expecting and what json response should I expect? What fields will be available for me to parse? Is there an example for each API call?

I have used an example to get all L3 rules but the request is different than what i see for Port Forwarding.

**Comment by shiyuechengineer** [comment]
You can find that endpoint's documentation [here](https://developer.cisco.com/meraki/api-v1/#!update-network-appliance-firewall-port-forwarding-rules), along with a sample Python library code snippet on the right by going to _Template > Meraki Python Library_.

**Comment by kustomservices** [comment]
Thanks. I was looking at the non beta version. But when I attempt to use the

**Comment by shiyuechengineer** [comment]
It's similar in v0: https://developer.cisco.com/meraki/api/#!update-network-port-forwarding-rules

If you're still getting an error, please post the full trace to help debug.

**Comment by kustomservices** [comment]
Maybe it would help if I gave you example of what I am trying to do:
`# This script is designed to get a list of all organizations
# in our system and look up their port forward rules
# Updated based on the latest Dashboard API


import meraki
import time
import sys
import config
import requests
import csv
import logging
import os
from datetime import datetime

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def main():
        #Turn on Logging
        logging.basicConfig(level=logging.INFO)
        logger = logging.getLogger(__name__)
        import pdb; pdb.set_trace()
        #Setup meraki dashboard connection
        dashboard = meraki.DashboardAPI(
                api_key=config.meraki_api_key,
                base_url='https://api-mp.meraki.com/api/v0/',
                output_log=False,
                log_file_prefix=os.path.basename(__file__)[:-3],
                log_path='',
                print_console=False,
                suppress_logging=False
        )
        myOrgs = dashboard.organizations.getOrganizations()
        total = len(myOrgs)
        print(f'{bcolors.OKBLUE}Processing...Organizations...{bcolors.ENDC}\n',sep='', end='', flush=True)
        myOrgs = sorted(myOrgs, key=lambda x:x['name'])
        for org in myOrgs:
                # Get list of networks in organization
                try:
                        networks = dashboard.networks.getOrganizationNetworks(org['id'])
                except meraki.APIError as e:
                        print(f'{bcolors.WARNING}Meraki API error: {e}')
                        print(f'status code = {e.status}')
                        print(f'reason = {e.reason}')
                        print(f'error = {e.message}{bcolors.ENDC}')
                        continue
                except Exception as e:
                        print(f'{bcolors.WARNING}some other error: {e}{bcolors.ENDC}')
                        continue
                print(f'{bcolors.OKGREEN}'+org['name']+ f'{bcolors.ENDC}\n', sep='', end='', flush=True)
                for net in networks:
                        try:
                                fw_rules = MXPortForwardingRules(net['id'])
                        except meraki.APIError as e:
                                print(f'{bcolors.WARNING}Meraki API error: {e}')
                                print(f'status code = {e.status}')
                                print(f'reason = {e.reason}')
                                print(f'error = {e.message}{bcolors.ENDC}')
                                continue
                        except Exception as e:
                                print(f'{bcolors.WARNING}some other error: {e}{bcolors.ENDC}')
                                continue
                        else:
                                logger.info(fw_rules)
                                for rule in fw_rules:
                                        logger.info(rule)                                                      
print("Done!")

if __name__ == '__main__':
    start_time = datetime.now()
    main()
    end_time = datetime.now()
    print(f'\nScript complete, total runtime {end_time - start_time}')
`
The result is:
`some other error: name 'MXPortForwardingRules' is not defined`

**Comment by sambyers** [comment]
@kustomservices It may be a simple typo: Construct your call for MXPortForwardingRules the same way you did for getOrganizationNetworks by using the dashboardAPI object: dashboard.MXPortForwardingRules.getNetworkPortForwardingRules('network-id'). HTH

**Comment by shiyuechengineer** [comment]
Where are you getting `MXPortForwardingRules` from? In v0 of the library, you'll need to make a call to the function `dashboard.mx_port_forwarding_rules.updateNetworkPortForwardingRules` to change the port forwarding rules, or in your case, `dashboard.mx_port_forwarding_rules.getNetworkPortForwardingRules(net['id'])` to retrieve them.

**Comment by kustomservices** [comment]
Thanks. That is the help I was needing. I can see MXPortForwardingRules.py in the api folder but I did not know how to make the call. I will give this a shot tomorrow.

**Comment by kustomservices** [comment]
Thanks. That worked.
