### ISSUE TITLE
Possible issue with large client numbers in 1.0.0b12

### ISSUE THREAD

**Issue by jc516229** [meraki/dashboard-api-python#105]
A script that runs daily to gather client usage stats gave an error few nights ago, again last night, and several times today when testing to track down...
 
aiomeraki.networks.getNetworkClients raises an exception "argument of type 'URL' is not iterable"

t = 24 * 60 * 60
clients = await aiomeraki.networks.getNetworkClients(net['id'], timespan=t, perPage=1000, total_pages="all")

Testing shows out of three orgs and > 200 networks only seeing the issue on a single 'appliance' network that has a large number of clients - when checked in Dashboard over 3100 clients seen in last 24 hours, maybe it's triggering an issue in the page handling?

The script has been running ok for several weeks, only seen this since 1.0.0b12, but it may simply be that client numbers haven't been as high previously.

**Comment by shiyuechengineer** [comment]
Can you send the raw log file to me please? shiychen@cisco.com

**Comment by jc516229** [comment]
Issue is resolved in https://github.com/meraki/dashboard-api-python/commit/0ad00acb115bcabcc9f40e3c4acfd7475b789378
