### ISSUE TITLE
API errors and messages

### ISSUE THREAD

**Issue by Carmezim** [meraki/dashboard-api-python#106]
Hey folks, thanks for the great work with the SKD, it's been definitely an useful interface for the Meraki API.

I was wondering how do I retrieve the status codes and error messages so I can do some further processing in my code. 

Thank you

**Comment by shiyuechengineer** [comment]
Thanks Adriano; you can find an example of that on lines 37-39 [here](https://github.com/meraki/dashboard-api-python/blob/master/examples/org_wide_clients_v1.py#L37).

**Comment by Carmezim** [comment]
Sweet, thank you.
