### ISSUE TITLE
Pagnation Error

### ISSUE THREAD

**Issue by krazeeEyez** [meraki/dashboard-api-python#108]
argument of type 'URL' is not iterable when trying to get second and higher pages.

 # Ensure proper base URL
        if "meraki.com" in url:
            abs_url = url
        else:
            abs_url = self._base_url + url

changing - if "meraki.com" in str(url):

works fine

**Comment by krazeeEyez** [comment]
forgot to add this is with rest_session in the ascyno version

**Comment by shiyuechengineer** [comment]
I don't see the issue here with pagination. Can you share the log file where you run into an error? Thanks. shiychen@cisco.com

**Comment by TKIPisalegacycipher** [comment]
@krazeeEyez still having this issue with the most recent version of the SDK?

**Comment by krazeeEyez** [comment]
Yep. see it was fixed and have been using aysync without issue. Thanks!
