### ISSUE TITLE
Get Signal information of Client?

### ISSUE THREAD

**Issue by baonq243** [meraki/dashboard-api-python#110]
Can i get Channel, WiFi Signal Strength of a client.

![Screen Shot 2020-08-05 at 11 55 12](https://user-images.githubusercontent.com/5095778/89373313-8ccf4b00-d712-11ea-827e-e36a32bcda15.png)

**Comment by rupertwever** [comment]
"""
https://developer.cisco.com/meraki/api-v1/#!get-network-wireless-signal-quality-history
Returns signal quality (SNR/RSSI) over time for a device or network client
"""
import meraki

# Defining your API key as a variable in source code is not recommended
API_KEY = '6bec40cf957de430a6f1f2baa056b99a4fac9ea0'
# Instead, use an environment variable as shown under the Usage section
# @ https://github.com/meraki/dashboard-api-python/

dashboard = meraki.DashboardAPI(API_KEY)

network_id = 'L_646829496481105433'

response = dashboard.wireless.getNetworkWirelessSignalQualityHistory(
    network_id
)

print(response)
