### ISSUE TITLE
BasicAuth for proxy request

### ISSUE THREAD

**Issue by avisual** [meraki/dashboard-api-python#114]
I can see  i can pass a proxy url, but can't see how I pass through auth=HTTPBasicAuth('user', 'pass') to allow requests to login to the proxy server? Is there any way I can do this?

**Comment by shiyuechengineer** [comment]
Isn't it a matter of setting `requests_proxy = 'https://user:password@proxyip:port'`?

**Comment by timway** [comment]
@avisual, you should be able to access the instantiation of Session from requests to perform the tie in for requests-ntlm2 via mount. Roughly something like:

```python
import meraki
dashboard = meraki.DashboardAPI()
dashboard._session._req_session.mount( ... )
dashboard._session._req_session.auth( ... )
```

After that you should be able to use your proxy. You can set the proxy URL via the normal constructor options.

**Comment by FortDigital** [comment]
> @avisual, you should be able to access the instantiation of Session from requests to perform the tie in for requests-ntlm2 via mount. Roughly something like:
> 
> ```python
> import meraki
> dashboard = meraki.DashboardAPI()
> dashboard._session._req_session.mount( ... )
> dashboard._session._req_session.auth( ... )
> ```
> 
> After that you should be able to use your proxy. You can set the proxy URL via the normal constructor options.

This was exactly what i was looking for today, It took me a while to work out the exact steps as i don't do a great deal of this kind of thing but went with:

```from requests_ntlm2 import (HttpNtlmAuth, HttpNtlmAdapter)
import meraki
dashboard = meraki.DashboardAPI(api_key=api_key,requests_proxy='http://proxy.server.co.uk:8080')
dashboard._session._req_session.mount('https://',HttpNtlmAdapter('Domain\Username','Password'))
dashboard._session._req_session.auth = HttpNtlmAuth('Username','Password')
```

I then had the added bonus of having to bypass Certificate Validation (temporarily) as this particular proxy also has SSL inspection on it:

`dashboard._session._req_session.verify = False`

Ill be replacing that line with the correct cert store once i work that piece out!

**Comment by avisual** [comment]
Thank you guys. Means I don’t have to keep screwing around with being off or on the VPN.
