### ISSUE TITLE
v1.1.0 output_log=False still generates log file

### ISSUE THREAD

**Issue by wilinger** [meraki/dashboard-api-python#117]
When output_log is set to False, a log file is still generated.  The only way to not generate a log file is setting suppress_logging to True which turns off all logging.

`
    dashboard = meraki.DashboardAPI(
        api_key=api_key,
        base_url='https://api-mp.meraki.com/api/v1/',
        output_log=False
    )
`

**Comment by shiyuechengineer** [comment]
Thanks for reporting the issue, which has now been fixed.
