### ISSUE TITLE
No Existing Documentation (That I can find)

### ISSUE THREAD

**Issue by bryaend** [meraki/dashboard-api-python#118]
I love this API so far. I'm starting on some dev work for my company but I've found that, outside of the example code, there's not a whole lot of documentation about the module as a whole. I've been able to limp my way through by reading through the actual module code and documentation but a published document library would be great. It would make it much faster to be able to follow the logic of the object relationships.

**Comment by thomaschristory** [comment]
Have you tried that little tool named google ? :)

https://developer.cisco.com/meraki/api-v1/

**Comment by bryaend** [comment]
> Have you tried that little tool named google ? :)
> 
> https://developer.cisco.com/meraki/api-v1/

I have! Unfortunately, the documentation is not fully written out to support the existing code structure. There are a few examples but nothing that specifies each class/object type that is supported by the module. E.g., which methods require which arguments, etc. This is standard among most python modules. The documentation along with digging through the module code tends to work but is inefficient.

**Comment by thomaschristory** [comment]
do you have an example of something you have trouble doing ?

**Comment by bryaend** [comment]
I can give an example: I wanted to find how to get the device loss and latency history for a given appliance. There's no specific mention of this functionality in the documentation but I was able to find it by running through the source code and finding the method I was looking for and then what arguments I needed. It would be great to have documentation similar to what is currently in the link you provided but that encompasses _all_ of the existing functionality.

**Comment by shiyuechengineer** [comment]
@bryaend, how about https://developer.cisco.com/meraki/api-v1/#!get-device-loss-and-latency-history?
If you want to see how to use it with the Python library, click "Template" on the right-hand side.

**Comment by TKIPisalegacycipher** [comment]
Hi there! Try loading up https://api.meraki.com/api/v1/openapiSpec and
you'll see everything documented.

**Comment by bryaend** [comment]
Alright, I think I just need to do some more digging on that site. It didn't seem intuitive at the time but it appears I was missing something. Thanks to all of you for your input.
