### ISSUE TITLE
getnetworklist 'tags' = None causing JSON output failed to be parsed correctly

### ISSUE THREAD

**Issue by hardjopranoto** [meraki/dashboard-api-python#12]
Sample of current output as follows.

`meraki.getnetworklist(‘api_key’,organizationId)

Network Operation Successful - See returned data for results

[{'id': 'L_602356450160805778', 'organizationId': '596171', 'name': 'Heathcote Nth 28923', 'timeZone': 'Australia/NSW', 'tags': **None**, 'type': 'combined'}]`

This causes error when I try to convert the output from JSON to CSV as it couldn't recognise the word None

Can I request the output to be changed to:

[{'id': 'L_602356450160805778', 'organizationId': '596171', 'name': 'Heathcote Nth 28923', 'timeZone': 'Australia/NSW', 'tags': **'None'**, 'type': 'combined'}]`

**Comment by shiyuechengineer** [comment]
This behavior is due to the API call itself returning null, which in Python of course is None, so doesn't really relate to how this Python module is implemented. What you can do here is check for None for 'tags' and replace it with an empty string or something equivalent.
