### ISSUE TITLE
Unable to update IKEv2 non-Meraki VPN peer

### ISSUE THREAD

**Issue by gdrapp** [meraki/dashboard-api-python#121]
Using the updateOrganizationApplianceVpnThirdPartyVPNPeers function to update an existing IKEv2 non-Meraki VPN peer I'm receiving the following error from the API: 

[ERROR] 2020-10-12T14:39:36.218Z        a6641ee4-65eb-11a6-94f9-cbd93d0626f2    appliance, updateOrganizationApplianceVpnThirdPartyVPNPeers - 400 Bad Request, {'errors': ['Peer "Zscaler Test": Invalid IPsec policy preset. Must be one of the following: default, aws, or azure.', 'Peer "Zscaler Test": Empty IPsec policy config.']}

Here's the peer data submitted to the updateOrganizationApplianceVpnThirdPartyVPNPeers function:
{'peers': [{'name': 'Zscaler Test', 'publicIp': '165.225.208.38', 'privateSubnets': ['0.0.0.0/0'], 'secret': 'xxxxxx', 'ikeVersion': '2', 'networkTags': ['Zscaler_Net'], 'ipsecPoliciesPreset': 'zscaler'}]}

It appears the API can't handle the new IKEv2 presets and is only allowing the old aws or azure options.

**Comment by shiyuechengineer** [comment]
Hi Greg, this is an issue with that particular API endpoint, which affects how this function in the Python module behaves. Can you please open up a case with Meraki Support on that root issue? Thanks.

**Comment by TKIPisalegacycipher** [comment]
Please open a new issue if you continue to have this problem.
