### ISSUE TITLE
updateNetworkWirelessAlternateManagementInterface returns  500 error

### ISSUE THREAD

**Issue by avisual** [meraki/dashboard-api-python#123]
Morning,

I'm trying to disable the Alternate Management Interface

`response = dashboard.wireless.updateNetworkWirelessAlternateManagementInterface(network.id,**data)`

data is a dict objects containing {"enabled": false}. but this is returning a error:

_WARNING > wireless, updateNetworkWirelessAlternateManagementInterface - 500 Internal Server Error, retrying in 1 second_

**Comment by TKIPisalegacycipher** [comment]
Still having this issue?

If so, does the network ID start with L_ or N_?

**Comment by TKIPisalegacycipher** [comment]
Seeing no response, I will close this issue. Please open a new issue with steps to reproduce if you continue to see this problem.
