### ISSUE TITLE
Questions about API default values for  updateNetworkWirelessSsid and returned responses with getNetworkWirelessSsid and

### ISSUE THREAD

**Issue by avisual** [meraki/dashboard-api-python#124]
I am writing some clone/backup functionality with the API but am finding some issues with data such as:

`dashboard.wireless.getNetworkWirelessSsid` and `dashboard.wireless.updateNetworkWirelessSsid` the get returns data with encryption mode = 'wpa-eap' but the update will not allow you to use the same data to update and wants 'wpa' is this a bug?  I know I can just replace but wondering if this just me using the API incorrectly? 

I am also seeing default values from the dashboard returned as None with gets while there a default value show in the browser. example of this are radiusFailoverPolicy and radiusLoadBalancingPolicy in the same function getNetworkWirelessSsid data.

last question is with regards to the dashboard.wireless.updateNetworkWirelessSsidFirewallL3FirewallRules in the browser using the dashboard I can set the Destination as 'Local LAN' but am unable to use this as a rule destination when using the API

![image](https://user-images.githubusercontent.com/810498/96143208-c97da680-0efa-11eb-9e4d-563d626de7c3.png)

error from api is 
{'errors': ['At least one of your firewall rules is invalid: "ssid[firewall_rules][0][dst_cidr] Destination address must be an IP address or a subnet in CIDR form (e.g. \'192.168.1.0/24\'), or \'any\'".']}
 
when passing the following data

![image](https://user-images.githubusercontent.com/810498/96143515-11043280-0efb-11eb-80c5-d0644d82585c.png)

Happy to split this question out if it helps or answer any other questions

John

**Comment by avisual** [comment]
sorry missed this with regards to the default and Local Lan comment. "An ordered array of the firewall rules for this SSID (not including the local LAN access rule or the default rule)." sorry about that

**Comment by TKIPisalegacycipher** [comment]
You're right, this is an issue with the API, unfortunately. Please open a ticket with Meraki Support, provide the same detail, and mention that the API team already discussed this with the MR team and they will fix (no ETA). Since this is not an SDK issue, I will close this.
