### ISSUE TITLE
Firewall Rules Return 404 For Some Networks

### ISSUE THREAD

**Issue by Carmezim** [meraki/dashboard-api-python#132]
Hey guys, so it happens occasionally when I've got an MR network, no MX devices, and I am able to perform a GET to L3 Firewall rules and get it successfully. Other times occasionally a similar MR network returns 404s for GET L3 Firewall rules. 

Any clue what could be happening or if I might be missing something config wise even?

Thank you

**Comment by TKIPisalegacycipher** [comment]
Hi Adriano,

Could you provide an example GET URL for this?

**Comment by Carmezim** [comment]
Hey @TKIPisalegacycipher thanks for your prompt reply.

Sure:

```
GET https://n320.meraki.com/api/v1/networks/N_743093938516131883/appliance/firewall/l3FirewallRules
```

**Comment by TKIPisalegacycipher** [comment]
The appliance scoped endpoints are intended for use with MX appliances so
if the networks in question don't contain any MX appliances then I'm not
sure why they would be relevant to your MR appliances.

Wireless networks have SSID scoped layer 3 firewall rules and associated
endpoints. Are you intending to do wireless layer three rules or appliance
layer three rules?

**Comment by Carmezim** [comment]
Thanks again for your reply @TKIPisalegacycipher.

You're correct. It's interesting though that some networks as I've mentioned only with MRs still return the L3 Firewall Rules or just don't return a 404 when requested. 

So it would be unintentional the L3 endpoints return for non MXs? 

For example, this below returns successfully:
```
https://n320.meraki.com/api/v1/networks/L_743093938516135770/appliance/firewall/l3FirewallRules
```

**Comment by TKIPisalegacycipher** [comment]
The difference is between a combined network (which starts with L_) and a
device-specific network (which starts with N_).

I bet this is why you're seeing the difference. It sounds like intended
behavior since combined networks are intended to work for all product types.

**Comment by Carmezim** [comment]
Ah okay I see, that's good to know. Thanks for that info.

I was wondering then for a network to be combined we don't need necessarily to have an MX in it then, it's based on product types set in the network's config?

**Comment by TKIPisalegacycipher** [comment]
Right, the network type simply determines what types of devices it can
contain.

**Comment by Carmezim** [comment]
Thank you so much for all the clarifications @TKIPisalegacycipher. That was really helpful.


Have a great day :)
