### ISSUE TITLE
Cellular Configuration

### ISSUE THREAD

**Issue by Carmezim** [meraki/dashboard-api-python#136]
Hey,

I have a question regarding devices with cellular enabled as MX68CW-NA. 

I was wondering if when using that device model only for cellular, if there are any endpoints we need to configure or enable this feature or it would be automatically enabled/pre-configured in the device itself when inserting a SIM.

Thank you so much.

**Comment by TKIPisalegacycipher** [comment]
Hi @Carmezim. Unfortunately the SDK issues tracker is not a great place to get advice on using product-specific features; instead it is intended to track issues with the SDK itself. Instead, I recommend posting your question in the Meraki community forum, probably in the MX-specific forum.

MX forum: https://community.meraki.com/t5/Security-SD-WAN/bd-p/security
MG forum: https://community.meraki.com/t5/Wireless-WAN/bd-p/wireless-wan
API forum: https://community.meraki.com/t5/Developers-APIs/bd-p/api
