### ISSUE TITLE
Cannot retrieve multiple pages when using sm.getNetworkSmDevices

### ISSUE THREAD

**Issue by lsellin** [meraki/dashboard-api-python#139]
Hi!
I have found out that it is not possible to use pagination when using getNetworkSmDevices (using API v1) to retrieve a list of devices when you have more than 1000 devices: the result is a list (of devices), and no "next" link or startingAfter parameter is returned that would allow to get the following page. The only solution to retrieve devices when you have more than 1000 devices  is to use handle the http requests directly. Is that expected?

Laurent

**Comment by TKIPisalegacycipher** [comment]
Hi @lsellin and thank you for reporting this. Could you outline the steps you take to reproduce this problem? As many specifics as you can provide would be appreciated.

**Comment by lsellin** [comment]
Hi!
I am just making a call to retrieve devices:
devices = dashboard.sm.getNetworkSmDevices(network_id, scope=scope, totalPages='all')
It returns a list of dictionary objects (each dictionary being a device). When more than 1000 devices are expected, with the python SDK, there is no way to navigate across pages using the prev/next/first/last links which is available when using the REST API: you can only get the first page of 1000 devices.

**Comment by TKIPisalegacycipher** [comment]
Hi @lsellin, this is a good example of a paginated endpoint. To move to the next page you make a subsequent GET specifying the appropriate integer ID(s).

It may be helpful to review the [docs on pagination, here](https://developer.cisco.com/meraki/api-v1/#!pagination/how-does-pagination-work-in-the-dashboard-api). 

For further reading, examine the docstrings on the smDevices function you mentioned, [in the source code](https://github.com/meraki/dashboard-api-python/blob/master/meraki/api/sm.py).

Please do open a new issue if you find a malfunction with the SDK!

**Comment by lsellin** [comment]
Thanks @TKIPisalegacycipher !
Looking into this, I realize it was due to a typo in my code: I had been using totalPages='all' instead of total_pages='all'! This simply returns the whole list of devices, without even the need to paginate.
Thanks again!
