### ISSUE TITLE
Minimal Repo Testing

### ISSUE THREAD

**Issue by PackeTsar** [meraki/dashboard-api-python#142]
Recently released v1.6.0 is breaking due to some basic syntax errors. The same thing happened in v1.4.2. Can we set up some code testing to prevent these kinds of errors from being left in the repo to extended periods of time?

Just integrating with Travis-CI and running a installation of the repo and a basic import should help here.

**Comment by TKIPisalegacycipher** [comment]
Thanks for the feedback.
