### ISSUE TITLE
Device Update Endpoint Delay

### ISSUE THREAD

**Issue by Carmezim** [meraki/dashboard-api-python#151]
**Current Behavior:**
Whenever a device is claimed, and a subsequent PUT request is made to `/devices` endpoint to update a device, the endpoint returns 404 for all attempts up to several minutes after the device has been claimed, until is then able to actually update the device returning a 200. 

 

**Expected Behavior:**
Able to update a device info after the device has been claimed into a network without several minutes delay.

 

This was attempted with the SDK, using the API directly and direct HTTP with curl/Insomnia/Postman etc.

 

Steps to reproduce:
1. Create an organization network
2. Claim device into network
3. Try to update the device name (for instance) through the update device endpoint.

 

Any insights on that behavior or if anyone else experienced it would be great. 
Not sure if the best place to post this issue as it seems to be the actual Dashboard API, so if should be elsewhere please advise.

 

Thank you

**Comment by TKIPisalegacycipher** [comment]
Hi @Carmezim. This is an API-side limitation, documented in the relevant endpoint. Programmatically, one would add a delay to handle this.

Since this is not an issue with the SDK, I will close this case.

**Comment by Carmezim** [comment]
Thanks for the reply.

Is it documented?

https://developer.cisco.com/meraki/api-v1/#!update-device


Could you please point me in the right documentation where this is at?

Thank you

**Comment by TKIPisalegacycipher** [comment]
Hi @Carmezim, 

In https://api.meraki.com/api/v1/openapiSpec, under the claim endpoint docstrings:
` "/networks/{networkId}/devices/claim": {
      "post": {
        "description": "Claim devices into a network. (Note: for recently claimed devices, it may take a few minutes for API requsts against that device to succeed)",
        "operationId": "claimNetworkDevices",`
