### ISSUE TITLE
Upgrade from 1.7.2 to 1.10.0 - call to wireless.createNetworkWirelessSsidIdentityPsk() not working anymore

### ISSUE THREAD

**Issue by Philippe-Ragon** [meraki/dashboard-api-python#158]
I am making this call in one of my script:
wireless.createNetworkWirelessSsidIdentityPsk(netID,
                                                                            ssidNumber,
                                                                            mapping['name'],
                                                                            mapping['passphrase'],
                                                                            policyID)

When I use package 1.7.2 it is working fine.
With an upgrade to 1.10.0 I am getting the error message :
createNetworkWirelessSsidIdentityPsk() takes 5 positional arguments but 6 were given

Downgrading to 1.7.2 solves the issue

**Comment by TKIPisalegacycipher** [comment]
Hi @Philippe-Ragon, one of the params on this endpoint has changed from required to optional. While not a breaking change for the API itself, I see how using positional arguments that would have resulted in this. 

Just to confirm that this is the reason for the issue, please change your arguments to keyword arguments instead, and let me know if you continue to have the problem.

**Comment by Philippe-Ragon** [comment]
Hi John,

Could you please specify which arguments have to be changed from positional to keyword ?
And could you please specify the keywords ?

Philippe Ragon
+33 611 700 152

De : John M. Kuchta ***@***.***>
Envoyé : jeudi 17 juin 2021 18:13
À : meraki/dashboard-api-python ***@***.***>
Cc : Philippe RAGON ***@***.***>; Mention ***@***.***>
Objet : Re: [meraki/dashboard-api-python] Upgrade from 1.7.2 to 1.10.0 - call to wireless.createNetworkWirelessSsidIdentityPsk() not working anymore (#158)

________________________________
WARNING: This is an external email. Shall you have any doubt, report any suspicious e-mail by clicking on the "Report suspicious e-mail" button in Outlook.
________________________________


Hi @Philippe-Ragon<https://urldefense.com/v3/__https:/github.com/Philippe-Ragon__;!!Lt0KOR8!A65ZQKAIVHF3UJTERj_biw3QyccLFvPd6uvNktR6z5pOBi3df-A7Vd_xJd64W_1B0zelFkCu4hpB$>, one of the params on this endpoint has changed from required to optional. While not a breaking change for the API itself, I see how using positional arguments that would have resulted in this.

Just to confirm that this is the reason for the issue, please change your arguments to keyword arguments instead, and let me know if you continue to have the problem.

**Comment by TKIPisalegacycipher** [comment]
For this test, change them all to keyword args. You would have to read the docs to see the names of the args though, that's outside the scope of an issue report.

**Comment by Philippe-Ragon** [comment]
The only doc I am aware of is the one online : https://developer.cisco.com/meraki/api-v1/#!create-network-wireless-ssid-identity-psk
It is still referring to positional parameters.
Looking at the code I found keywords for 3 parameters ==> I changed the call to the endpoint into
wireless.createNetworkWirelessSsidIdentityPsk(netID,
                                                                            ssidNumber,
                                                                            name=mapping['name'],
                                                                            passphrase=mapping['passphrase'],
                                                                            groupPolicyId=policyID)

It is working with both package v1.7.2 and v1.10.0

Philippe Ragon
+33 611 700 152

De : John M. Kuchta ***@***.***>
Envoyé : jeudi 17 juin 2021 19:18
À : meraki/dashboard-api-python ***@***.***>
Cc : Philippe RAGON ***@***.***>; Mention ***@***.***>
Objet : Re: [meraki/dashboard-api-python] Upgrade from 1.7.2 to 1.10.0 - call to wireless.createNetworkWirelessSsidIdentityPsk() not working anymore (#158)

________________________________
WARNING: This is an external email. Shall you have any doubt, report any suspicious e-mail by clicking on the "Report suspicious e-mail" button in Outlook.
________________________________


For this test, change them all to keyword args. You would have to read the docs to see the names of the args though, that's outside the scope of an issue report.

**Comment by TKIPisalegacycipher** [comment]
Thank you for confirming!
