### ISSUE TITLE
incompatible error when install meraki package

### ISSUE THREAD

**Issue by hoyeunglee** [meraki/dashboard-api-python#16]
C:\Users\martlee2\Documents>pip install --upgrade requests
Requirement already up-to-date: requests in c:\python27\lib\site-packages (2.18.4)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests) (3.0.4)
Requirement not upgraded as not directly required: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests) (2018.4.16)
Requirement not upgraded as not directly required: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests) (1.22)
Requirement not upgraded as not directly required: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests) (2.6)
dhclientlist 0.0.6 has requirement requests==1.2.3, but you'll have requests 2.18.4 which is incompatible.
pyem7 0.0.dev1 has requirement requests==2.7.0, but you'll have requests 2.18.4 which is incompatible.

C:\Users\martlee2\Documents>pip install meraki
Requirement already satisfied: meraki in c:\python27\lib\site-packages (0.30)
dhclientlist 0.0.6 has requirement requests==1.2.3, but you'll have requests 2.18.4 which is incompatible.
pyem7 0.0.dev1 has requirement requests==2.7.0, but you'll have requests 2.18.4 which is incompatible.

and how to download csv  with the api
for 
manage/usage/list

**Comment by shiyuechengineer** [comment]
Hi, you need to install this with Python 3, not Python 2. Go through Exercise A [here](https://create.meraki.io/build/automation-with-python-api-lab/) to setup the installation.

To retrieve clients, you can use [this API call](https://api.meraki.com/api_docs#list-the-clients-of-a-device-up-to-a-maximum-of-a-month-ago), which would be the getclients function in the module.

**Comment by sorscode** [comment]
hoyeunglee - The API doesn’t supply that information that you are asking about. That would be a feature Meraki would have to build into the API call. With this API call you are specifying a timeframe and getting data back for that specific time frame. 

Unlike some cloud providers that supply APIs and you get the same data back as you see in the dashboard, Meraki does not.

**Comment by hoyeunglee** [comment]
What is length of period of data when run this api ?

I get it , I only need to save file using current date at 12:02am every day then every day data is different

**Comment by sorscode** [comment]
hoyeunglee - below I have copied and pasted the curl command you used. If you notice at the end you specify a “timespan=86400”. That would give you the last 24hrs (86400). If memory serves me right you can specify up to 30 days (2592000). 

curl -L -H 'X-Cisco-Meraki-API-Key ..... -X GET -H 'Content-Type: application/json' 'https://api.meraki.com/api/v0/devices/Q2LD-D8HX-JER5/clients?timespan=86400'

**Comment by hoyeunglee** [comment]
Thank you 
Script succeed
