### ISSUE TITLE
how to get the columns like these?

### ISSUE THREAD

**Issue by hoyeunglee** [meraki/dashboard-api-python#17]
```
myNetworks = meraki.getnetworklist(apikey, orgid)
result = ""
for networkdevicelist in myNetworks:
    networkid = networkdevicelist["id"]
    deviceList = meraki.getnetworkdevices(apikey, networkid)
    for devices in deviceList:
        serialnum = devices["serial"]
        clientList = meraki.getclients(apikey,serialnum)
        for clients in clientList:
            d = clients.copy()
            d.update(devices)
            d.update(networkdevicelist)
            result = result + str(d) + ","
```

i can get

`w.writerow([row['usage'], row['id'], row['description'], row['mdnsName'], row['dhcpHostname'], row['mac'], row['ip'], row['vlan'], row['switchport'], row['lanIp'], row['serial'], row['lat'], row['lng'], row['address'], row['name'], row['model'], row['networkId'], row['organizationId'], row['timeZone'], row['tags'], row['type']])
`
how to get columns below? 
there are first seen and last seen date time

![image](https://user-images.githubusercontent.com/5094741/39659187-c93361da-5055-11e8-8939-6e19913ffef8.png)

**Comment by sorscode** [comment]
hoyeunglee - To receive all those columns, that would be a feature request with Meraki. You could reach out to your Meraki Account Manager and request a feature request. I have a large number of requests in.

**Comment by hoyeunglee** [comment]
I am using python to get data but there is no length of period to specify
How to specify this like curl command?

**Comment by sorscode** [comment]
hoyeunglee - You would specify it in your code:
`clientList = meraki.getclients(apikey,serialnum)`

 It would look something like this:
`clientList = meraki.getclients(apikey,serialnum,timestamp=86400)`

Here is the definition from meraki.py
`def getclients(apikey, serialnum, timestamp=86400, suppressprint=False):`

As you can see from the definition there are 4 objects you can specify. Two are mandatory and two are optional.

apikey - mandatory
serialnum - mandatory
timestamp - optional
suppressprint - optional

The two optional ones already contain values. You can change the value by your call. I gave the timestamp a value of 86400 as an example to modify yours to, so you get the idea, but you can use up to 30 days.

Let me know if this helps.

**Comment by hoyeunglee** [comment]
I get it.

I heard from my colleague that there is no support in meraki 
How do account manager request ?

**Comment by shiyuechengineer** [comment]
Please 1) make a wish in Dashboard, & 2) file a feature request with your account team. Thanks!
