### ISSUE TITLE
Is the "Get Network Network Health Channel Utilization" endpoint available via the Meraki SDK?

### ISSUE THREAD

**Issue by obrigg** [meraki/dashboard-api-python#172]
GET /networks/{networkId}/networkHealth/channelUtilization

https://developer.cisco.com/meraki/api-v1/#!get-network-network-health-channel-utilization

**Comment by TKIPisalegacycipher** [comment]
Hi @obrigg you can find the info in that same docs site, hit the "Template" button.
![image](https://user-images.githubusercontent.com/3820074/142246745-5def7747-1438-4ae9-9c36-9b50f3b00f97.png)
