### ISSUE TITLE
Question: Retrieve port transceiver information for switches?

### ISSUE THREAD

**Issue by jeremyschulman** [meraki/dashboard-api-python#174]
Hi Team - I would like to use the API to retrieve information about installed transceivers for devices that support pluggable SFPs.  For example, the MS120 on the Dashboard portal, I see:

![image](https://user-images.githubusercontent.com/2607956/145695864-8d362cec-5c0c-4506-ad67-9193a7ddbc8d.png)

But when I retrieve the port status via the API there is no information about the transceiver; for example:

![image](https://user-images.githubusercontent.com/2607956/145695897-e9e84529-145c-4eb0-8543-dd1b8d5349fd.png)

I appreciate any guidance or suggestions you could offer.  Thank you!

**Comment by TKIPisalegacycipher** [comment]
Hi Jeremy, the best place to ask this type of question about the API's capabilities is in the [community forum](https://community.meraki.com/t5/Developers-APIs/bd-p/api). Thanks for raising this and I hope to see you there!
