### ISSUE TITLE
Question: How to retrieve the operating status of MX ports 3-12

### ISSUE THREAD

**Issue by jeremyschulman** [meraki/dashboard-api-python#175]
Hi Team,

On an MX device I can see the port status (up/down) indicated on the Dashboard, for example:

![image](https://user-images.githubusercontent.com/2607956/145697478-2e399de4-1f4d-467a-8888-02a485c17257.png)

Could you please direct me to which API I should be using to obtain these status values?  I've tied the switch port status, which work for the MS120 for example, but does not work for the MX.

I appreciate your guidance.

Thank you!
-- Jeremy

**Comment by TKIPisalegacycipher** [comment]
Hi @jeremyschulman since this tracker is for SDK issues allow me to direct you to our community where you can ask the same and get an answer more quickly. Thank you for your understanding.

https://community.meraki.com/t5/Developers-APIs/bd-p/api
