### ISSUE TITLE
Follow up on Issue # 170 (updateNetworkWirelessRfProfile - perSsidSettings)

### ISSUE THREAD

**Issue by vmunnz93** [meraki/dashboard-api-python#176]
In the latest version of the library (v1.15.0), investigating *dashboard-api-python/meraki/api/wireless.py* [here](https://github.com/meraki/dashboard-api-python/blob/9f0b4df02fba737289154d9e31d75bd262194117/meraki/api/wireless.py), and locating the code for *[updateNetworkWirelessRfProfile](https://drive.google.com/file/d/1pq0B4X0qjLlnddP-bP_dhvJpqQ6Fqhua/view?usp=sharing)*, we see that ```'perSsidSettings'``` is not included in ```body_params```.  

This is affecting user's (@Philippe-Ragon) ability to modify per-SSID ```bandOperationMode``` & ```bandSteeringEnabled``` configurations for APs mapped to non-default RF profiles. 

**The ask:** Could we update the repo that allows the ```perSsidSettings``` field to be updated?

**Comment by TKIPisalegacycipher** [comment]
The library has now been updated for the latest API release v1.18.0. Please open a new issue if you have any other questions.

**Comment by Philippe-Ragon** [comment]
The library has been updated but the issue is still present with 1.18.1
When you call updateNetworkWirelessRfProfile() with bandSelectionType set to 'ssid' you have no way to specify 'perSsidSettings'

Adding this keyword in variable body_params solves the issue.
