### ISSUE TITLE
Follow up on issue #170 related to updateNetworkWirelessRfProfile - perSsidSettings()

### ISSUE THREAD

**Issue by Philippe-Ragon** [meraki/dashboard-api-python#180]
The library has been updated to v1.18.1 but issue #170 is still present.
When you call updateNetworkWirelessRfProfile() with bandSelectionType set to 'ssid' you have no way to specify 'perSsidSettings'

Adding this keyword in variable body_params solves the issue.

**Comment by TKIPisalegacycipher** [comment]
Thanks for raising this! Looks like a bug in the spec, rather than the library. We'll update the library once the spec is fixed.

**Comment by TKIPisalegacycipher** [comment]
Now available in library version 1.18.2.
