### ISSUE TITLE
moveMapMarker is not working for China region

### ISSUE THREAD

**Issue by koladiya** [meraki/dashboard-api-python#189]
Meraki version used for this test = 1.18.2 & 1.20.0

**Problem:**
`moveMapMarker=True` is not placing the device at the right lat & long for the given address in the china region only.
It is working correctly for another region(`base_url="https://api.meraki.com/api/v1/"`).

**Code snippet:**
```
import meraki

meraki_api = meraki.DashboardAPI(
   base_url="https://api.meraki.cn/api/v1/",
    suppress_logging=True,
)

attributes = {
    "name": "ap1",
    "address": "<china address>",
    "moveMapMarker": True,
}

res = meraki_api.devices.updateDevice(serial=<device-serial>, **attributes)
print(res)
```

We need to manually save the address & then it relocates the device on the map.
![image](https://user-images.githubusercontent.com/17511896/162921550-7a032cc2-bc5d-4f81-ad1a-33170358822e.png)

**Comment by TKIPisalegacycipher** [comment]
Hi @koladiya , please report this issue to Meraki support. This does not seem to be a library-specific issue and seems to affect the underlying API endpoint.
