### ISSUE TITLE
Add support for Policy Groups and Objects

### ISSUE THREAD

**Issue by szeestraten** [meraki/dashboard-api-python#191]
It would be great if support would be added for Policy Groups and Objects (also sometimes refered to as Network Groups and Objects) which was introduced in API [v1-11-0-beta-0](https://developer.cisco.com/meraki/whats-new/#!v1-11-0-beta-0/-organizations).

https://documentation.meraki.com/MX/Firewall_and_Traffic_Shaping/Network_Objects_Configuration_Guide

**Comment by TKIPisalegacycipher** [comment]
This feature will be added to this library once it is GA.

**Comment by szeestraten** [comment]
Hi again. Policy objects are now GA as of 2022-11-02.

**Comment by TKIPisalegacycipher** [comment]
All supported in version 1.27.0.
