### ISSUE TITLE
API endpoint does not allow updating DDNS prefix

### ISSUE THREAD

**Issue by pauseframes** [meraki/dashboard-api-python#195]
Issue:
When trying to change the prefix for Dynamic DNS through the API, it does not change it despite providing a 200 okay. 

Python version = 3.8/3.10.4
Meraki SDK Version = 1.25.0

Endpoint URL= https://developer.cisco.com/meraki/api-v1/#!update-network-appliance-settings

Problem:

When using SDK method: updateNetworkApplianceSettings(), dynamicDns does not update.

Example Code:

```
import meraki
import json
dashboard = meraki.DashboardAPI(API_KEY)

network_id = "network_id"

payload = json.dumps({"prefix": "test-me-hostname", "enabled": True})


response = dashboard.appliance.updateNetworkApplianceSettings(
    network_id,
    clientTrackingMethod="MAC address",
    deploymentMode="routed",
    dynamicDns=payload,
)



print(response)

```
logs:

2022-10-11 11:18:36       meraki:     INFO > appliance, updateNetworkApplianceSettings - 200 OK
{'clientTrackingMethod': 'MAC address', 'deploymentMode': 'routed'}

Returns 200 but does not change the dynamic DNS prefix.

**Comment by TKIPisalegacycipher** [comment]
I'm not able to reproduce this on my end; in fact, I'm seeing the desired behavior where supplying 'prefix' correctly updates the URL. Please let me know if you continue to have this problem.
