### ISSUE TITLE
Add Uptime feature

### ISSUE THREAD

**Issue by jacobjessup** [meraki/dashboard-api-python#196]
Is there anyway to add a feature to get AP uptime information?

**Comment by TKIPisalegacycipher** [comment]
Hi @jacobjessup this library will include such information if it is added to the public API. Since this is not an issue with the library I'll close this issue.

**Comment by BraydenNeale** [comment]
Hi @TKIPisalegacycipher 

The Meraki API documents and supports: https://developer.cisco.com/meraki/api-v1/get-organization-devices-boots-history/
Why isn't this generated into the SDK? I don't think its noted as Beta or Deprecated.
