### ISSUE TITLE
Change device LAN IP from DHCP to STATIC and assign an IP, mask ..

### ISSUE THREAD

**Issue by mathewfer** [meraki/dashboard-api-python#21]
Hi,

I started using your script and is very useful. I have a question ... just wondering ....
Is it possible to use a function call via REST API to change the below?

Device attributes:
1. Change DHCP to STATIC
2. Assign an IP address, mask and gateway

**Comment by shiyuechengineer** [comment]
Thanks. There isn't an API call today that accomplishes either of what you're asking, so in the meantime, please make a wish at the bottom-right of Dashboard!
