### ISSUE TITLE
Early Access Supported Calls

### ISSUE THREAD

**Issue by andy-shady-org** [meraki/dashboard-api-python#210]
Hi,

Will you accept a MR for early access calls to the Meraki API?

https://developer.cisco.com/meraki/api-v1/#!get-organization-appliance-uplinks-usage-by-network

The above is a big win for me, as it reduces the number of calls, in comparison to getNetworkApplianceUplinksUsageHistory, due to the large number of networks within organisations that I have.

Im not aware of the timeline that this call will move to being part of V1, and away from being early access however.

PR is here: https://github.com/meraki/dashboard-api-python/pull/209

Thanks

Andy

**Comment by TKIPisalegacycipher** [comment]
Hi @andy-shady-org,

Thanks for asking this! 

If you're not already familiar, [this post details the way the Early API Access program works](https://community.meraki.com/t5/Developers-APIs/UPDATED-Beta-testing-with-the-Meraki-Developer-Early-Access/m-p/145344#M5808) and helps shed light on why the early access calls are not included by default in this library.

However, [the library generator](https://github.com/meraki/dashboard-api-python/tree/main/generator) can be run on organizations with Early API Access, which would result in a library tailored to the given organization and would have the API calls available to that specific organization. You are free to generate and use such a library if you so choose.

With that in mind, the default library will not include Early API Access calls. Accordingly, I will close this request.

Kindly,
