### ISSUE TITLE
204-No Content error

### ISSUE THREAD

**Issue by fmunozmiranda** [meraki/dashboard-api-python#214]
**Describe how you confirmed the issue is with the library, and not with the API itself, or a server-side issue of some other kind.**
Using the `getOrganizationClientsSearch` function when getting a 204-No content code, you get the following error:
![image](https://github.com/meraki/dashboard-api-python/assets/93611708/865bad93-90aa-43ca-8f42-4d123c7004e9)

**Python version installed**
Python 3.10.5

**Meraki library version installed**
v1.33.0

**Have you reproduced the issue with the latest version of this library? And with the latest version of Python?**
Yes.

**OS Platform**
MacOS

**Expected behavior**
It should be able to handle a 204 - No content code.

**Comment by TKIPisalegacycipher** [comment]
Thank you for reporting this. The next release of the library will include this fix. Please feel free to modify your local library with the aformentioned change in the meantime.
