### ISSUE TITLE
tags not entering correctly

### ISSUE THREAD

**Issue by mycollablab** [meraki/dashboard-api-python#22]
When tags are entered for update device I am getting each letter as a separate tag instead of each word as a tag

**Comment by shiyuechengineer** [comment]
Hi, you want to pass in the tags as a list of strings, so something like:
`tags = ['Alpha', 'Beta', 'Charlie']`

**Comment by NoFliesOnYou** [comment]
Had same issue. Existing code changed 'Alpha' to 'A', 'l', 'p', 'h', 'a'. 
Expected 'Alpha'.
New pull request created as shown above. Tested in a Meraki environment.
