### ISSUE TITLE
'Wireless' object has no attribute 'getOrganizationWirelessDevicesEthernetStatuses'

### ISSUE THREAD

**Issue by jframeau** [meraki/dashboard-api-python#224]
**Python version installed**
Python 3.9.16

**Meraki library version installed**
Meraki dashboard API session initialized with these parameters: {'version': '1.27.0', 'api_key': ****', 'base_url': 'https://api.meraki.com/api/v1', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 60, 'action_batch_retry_wait_time': 60, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 2, 'simulate': False, 'be_geo_id': None, 'caller': None, 'use_iterator_for_get_pages': False}

**OS Platform**
Rocky Linux 9

**Describe the bug**
response = dashboard.wireless.getOrganizationWirelessDevicesEthernetStatuses(
AttributeError: 'Wireless' object has no attribute 'getOrganizationWirelessDevicesEthernetStatuses'

Code is from Meraki sandbox

#!/bin/env python
import meraki

# Defining your API key as a variable in source code is not recommended
API_KEY = '***'

dashboard = meraki.DashboardAPI(API_KEY)

organization_id = '***'

response = dashboard.wireless.getOrganizationWirelessDevicesEthernetStatuses(
    organization_id, total_pages='all'
)

print(response)

The weird thing from Meraki sandbox ( https://developer.cisco.com/meraki/api-v1/get-organization-wireless-devices-ethernet-statuses/ ) is that response has nothing to do with the spec:

Example:
  {
        "mac": "88:15:44:ab:b0:ae",
        "name": "CISCO_MR42_L111_159",
        "network": { "id": 564638803281661950 },
        "productType": null,
        "serial": "Q2KD-3BS7-L3GK",
        "status": null,
        "tags": [ "R1", "SandBox" ]
    }

jfr

**Comment by TKIPisalegacycipher** [comment]
Hi @jframeau please update your library to the current version. Your version of the library precedes the release of this endpoint.
