### ISSUE TITLE
Installation via PIP

### ISSUE THREAD

**Issue by kecorbin** [meraki/dashboard-api-python#23]
I had some issues installing via pip as it didn't pull dependencies, and could not import properly after installation.  

```
(tmp) ➜  /tmp pip install meraki
Collecting meraki
Installing collected packages: meraki
Successfully installed meraki-0.34
(tmp) ➜  /tmp python
Python 2.7.10 (default, Feb 22 2018, 22:42:27) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from meraki import meraki
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named meraki
>>> 

```

I added a setup.py and restructured slightly for what I think would be the required updates, feel free to PR if you like

https://github.com/meraki/dashboard-api-python/compare/master...kecorbin:master

**Comment by pocc** [comment]
You're using python (2.7.10) when python3 (3.6) is required for this project.

**Comment by kecorbin** [comment]
Regardless of 2.7/3.6, my issue was that `pip install meraki` did not drag the dependencies with it. 
```
Python 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from meraki import meraki
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kecorbin/VirtualEnvs/meraki/lib/python3.6/site-packages/meraki/meraki.py", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

I was simply suggesting an improvement to what is a pretty cool project.  Also the lib worked fine for me in 2.7 with the proposed changes.
