### ISSUE TITLE
batch.networks.removeNetworkDevices has the incorrect operation

### ISSUE THREAD

**Issue by rwilliams01123** [meraki/dashboard-api-python#241]
making the call you receive the following exception:
meraki.exceptions.APIError: organizations, createOrganizationActionBatch - 400 Bad Request, {'errors': ['create operation is unsupported for /networks/{network_id}/devices/remove.']}

Current code:
action = {
    "resource": resource,
    "operation": "create",
    "body": payload
}

Changing the operation to 'remove' fixes the issue.
Working code:
action = {
    "resource": resource,
    "operation": "remove",
    "body": payload
}

**Comment by TKIPisalegacycipher** [comment]
@rwilliams01123 thank you for reporting this. Thanks to your report I identified a number of other issues and you will see these fixed shortly. You will need to upgrade to 1.42.0 to resolve this issue.

**Comment by rwilliams01123** [comment]
Verified as working, thank you!
