### ISSUE TITLE
Minor Documentation Spelling Error

### ISSUE THREAD

**Issue by helpdeskdan** [meraki/dashboard-api-python#248]
appliance.py, line 890

<pre>
- accessPolicy (string): The name of the policy. Only applicable to Access ports. Valid values are: 'open', '8021x-radius', 'mac-radius', 'hybris-radius' 
</pre>
I believe you mean hybri**d**-radius as returned by getNetworkAppliancePorts
<pre>
[{'accessPolicy': 'hybrid-radius',
</pre>

Thanks for your work on this project, very useful

**Comment by helpdeskdan** [comment]
(Not that it matters - I see no way to set a radius server)

**Comment by TKIPisalegacycipher** [comment]
Thank you @helpdeskdan for reporting this. Please report this through the Meraki support team; this can only be fixed on the API side.
