### ISSUE TITLE
API Endpoint /organizations/{organizationId}/wireless/radio/autoRf/byNetwork Missing

### ISSUE THREAD

**Issue by Gieberzo** [meraki/dashboard-api-python#250]
**Describe how you confirmed the issue is with the library, and not with the API itself, or a server-side issue of some other kind.**
I looked through the most recent version of code and did not see that endpoint referenced

**Python version installed**
3.12

**Meraki library version installed**
1.45

**Have you reproduced the issue with the latest version of this library? And with the latest version of Python?**
yes

**Comment by TKIPisalegacycipher** [comment]
Hi @Gieberzo , is this operation GA? If it's not [here](https://github.com/meraki/openapi/raw/master/openapi/spec3.json), it's probably not GA yet. You can always check if something's GA by looking for it in the GA OAS.

Please feel free to reopen this if you find that it's GA.
