### ISSUE TITLE
Method returning HTTP Status Code: 404 - No returned data

### ISSUE THREAD

**Issue by craigbruenderman** [meraki/dashboard-api-python#26]
I've run into a few methods that return HTTP Status Code: 404 - No returned data, even though I can see data in the Dashboard that I would expect to be returned.

For instance,

>>> meraki.getnetworklist(apikey, orgid)
HTTP Status Code: 404 - No returned data

>>> meraki.getorginventory(apikey, orgid)
HTTP Status Code: 404 - No returned data

This orgid definitely has networks with devices in it that I can view from Dashboard. Using different orgid's and the same call may give me data, or may give me the 404.

Any ideas?

**Comment by craigbruenderman** [comment]
Easy fix... A handful of my Orgs didn't have API access enabled.

**Comment by mycollablab** [comment]
I'm having the same issue at random times.  I am cycling through a switch updating ports and sometimes will finish with no issue, but other times it gets stuck for a period of time with these errors.  Connectivity from my client seems good so I dont believe that would be the issue.

**Comment by pocc** [comment]
@mycollablab Can you post the text of the function calls you are making (sans API key of course).

**Comment by mycollablab** [comment]
I'm seeing it on updateswitchport() mainly.  I can rerun the script with the exact same data and it will pass.  Seems to have "blackout" moments where it won't work for a few minutes and then start working.  Makes troubleshooting really fun.

**Comment by mycollablab** [comment]
I found the issue.  When you add a switch to a network it must take 2min or so before you can configure the switch ports via the api.  I adjusted the work flow and have had the issues.
