### ISSUE TITLE
claimNetworkDevices with addAtomically fails with unexpected keyword argument

### ISSUE THREAD

**Issue by rasmusbirkelund** [meraki/dashboard-api-python#261]
Using the meraki package, installed using pip, when assigning devices to a network, and setting the keyword addAtomically to true, the call fails with unexpceted keyword error. 

According to API documentation on meraki.io, this is an optional parameter, although it is not listed in the API schema.
https://developer.cisco.com/meraki/api-v1/claim-network-devices/

<img width="635" alt="billede" src="https://github.com/meraki/dashboard-api-python/assets/42373139/e690f216-be4e-4118-a1f0-481ff1342cb8">

I'm calling the function in my script as such,
`    response = dashboard.networks.claimNetworkDevices(
        NetworkId, SerialsToAssign, 
        addAtomically=True
    )
    print(response)`

`(.venv) RHB@wopr AddDevicesToNetwork % pip show meraki
Name: meraki
Version: 1.46.0
Summary: Cisco Meraki Dashboard API library
Home-page: https://github.com/meraki/dashboard-api-python
Author: Cisco Meraki
Author-email: api-feedback@meraki.net
License: MIT
Location: /Users/RHB/Documents/dev-local/.../AddDevicesToNetwork/.venv/lib/python3.12/site-packages
Requires: aiohttp, requests
Required-by: 
(.venv) RHB@wopr AddDevicesToNetwork % 
(.venv) RHB@wopr AddDevicesToNetwork % python -V
Python 3.12.4
(.venv) RHB@wopr AddDevicesToNetwork % `

**Comment by TKIPisalegacycipher** [comment]
Hello @rasmusbirkelund thank you for reporting this. I believe this is fixed in 1.48.0 of the library. Would you mind updating your library and testing to confirm? Thank you kindly.

**Comment by TKIPisalegacycipher** [comment]
Seeing no response, closing as resolved.
