### ISSUE TITLE
Issue with dashboard.devices.getDevice in v1.50.0

### ISSUE THREAD

**Issue by rjhallinan** [meraki/dashboard-api-python#267]
**Describe how you confirmed the issue is with the library, and not with the API itself, or a server-side issue of some other kind.**
Ran the call dashboard.devices.getDevice(<Serial Number>) using version 1.49.0. Upgraded to v1.50.0 and get a Null response. No issue running using the actual requests library. Went back to v1.49.0 and no issue again.

**Python version installed**
Python 3.11.4

**Meraki library version installed**
1.50.0 (with issue) - reverted to 1.49.0 to regain functionality

**Have you reproduced the issue with the latest version of this library? And with the latest version of Python?**
Issue was new for me in 1.50.0 - not present in 1.49.0. I did not bother to change Python versions.

**OS Platform**
Windows

**Describe the bug**
Using dashboard.devices.getDevice(<Serial Number>) to retrieve device information. On v1.49.0 - properly returned data on the switch I was querying. Updated to 1.50.0 - and consistently returns None - no change made to how the call occurred. Return back to 1.49.0 - no issue.

**How can we replicate the problem you're reporting?**
Install v1.50.0
Establish a dashboard connection: dashboard = meraki.DashboardAPI()
Run a query against devices; dev_info = dashboard.devices.getDevice(SERIALNUMBERHERE)
Get 'None' as response.

Revert to 1.49.0
Establish a dashboard connection: dashboard = meraki.DashboardAPI()
Run a query against devices; dev_info = dashboard.devices.getDevice(SERIALNUMBERHERE)
Get  full dictionary of device info as response.

**Comment by TKIPisalegacycipher** [comment]
Hi @rjhallinan thank you for reporting this.

I checked the commit diff between 1.49 and 1.50 and there were no changes in the library code, so no sign of anything that would explain that behavior. I then tried to reproduce this issue with two different serials and didn't have any errors or None responses. 

Not sure if this is it, but remember the syntax would be `dashboard.devices.getDevices("serial-number-here")`. Does that help?

If not, do you have any other evidence that would suggest this is an issue with the library, so we could look into it?

**Comment by TKIPisalegacycipher** [comment]
Closing this, given the inability to reproduce.
