### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by tijssengier** [meraki/dashboard-api-python#27]
Hey guys,

This error is completely random.
I use the API to backup some parts of my organizations in meraki cloud.
Sometimes i get this error with backingup my switchports.
The problem is that it realy is not consistent when it happens.
Long story short, I build another PY file ready to restore the organization
Does anyone have an idea on this ?

Error:
***Backing up switchports
Traceback (most recent call last):
  File "back-all-org.py", line 363, in <module>
    write_switchports(apikey,row['id'], suppressprint)
  File "back-all-org.py", line 222, in write_switchports
    if port['name'] is not "":
TypeError: string indices must be integers

Code:

def write_switchports(file, apikey, networkid, suppressprint):
	switches = []

	devices=meraki.getnetworkdevices(apikey, networkid, suppressprint)
	file.write("\t# switchports\n")
	
	for device in devices:
		if "MS" in str(device['model']):
			switches.append(device)

	for switch in switches:
		file.write("\t# switch " + str(switch['name']) + "\n")
		file.write("\tprint(\"Restoring switchports\")")
		file.write("\t# https://dashboard.meraki.com/api_docs#switch-ports\n")
		portname = "None"
		porttags = "None"
		switchports = meraki.getswitchports(apikey, switch['serial'], suppressprint)
		for port in switchports:
			if port['name'] is not "":
				portname = "\""+str(port['name'])+"\""
			else: 
				portname = "None"

			if port['tags'] is not None:
				porttags = "\""+ port['tags']+"\""
			else:
				porttags= "None"

			file.write("\tmeraki.updateswitchport(apikey, \""+ str(switch['serial']) +"\", "+str(port['number'])+", "+ portname +", "+porttags+", "+str(port['enabled'])+", \""+str(port['type'])+"\", "+str(port['vlan'])+", "+str(port['voiceVlan'])+", \""+str(port['allowedVlans'])+"\", "+str(port['poeEnabled'])+", "+str(port['isolationEnabled'])+", "+str(port['rstpEnabled'])+', \"'+str(port['stpGuard'])+"\", "+str(port['accessPolicyNumber'])+", "+"suppressprint)\n")

		file.write("\n")

**Comment by pocc** [comment]
What is the value of switchports when this happens? You can determine this using a debugger like pdb or using print statements. 

Like as not, an error occurs and switchports is a str containing the errortext instead of the expected dict.
