### ISSUE TITLE
Alerts/HTTP Servers API calls

### ISSUE THREAD

**Issue by phate408** [meraki/dashboard-api-python#31]
I'm doing some work with scripting setting up alerts using webhooks. Having the alerts and HTTP server calls being exposed as part of this library would be helpful in that regard. #

**Comment by nielsvanhooy** [comment]
i added return HTTPS server and ADD HTTPS servers into my branch (im kinda new with GIT only programmed a closed of enviroment at work for meraki. but these 2 features are working in my branch as of now. starting works on alert calls. check back in a few weeks.
