### ISSUE TITLE
updatevlan no  DHCP option change

### ISSUE THREAD

**Issue by maximcoder** [meraki/dashboard-api-python#40]
# Update a VLAN
# https://api.meraki.com/api_docs#update-a-vlan
def updatevlan

does not include the change of he DHCP option like 

dhcpHandling - The appliance's handling of DHCP requests on this VLAN. One of: "Run a DHCP server", "Relay DHCP to another server", or "Do not respond to DHCP requests"
dhcpRelayServerIps - The IPs of the DHCP servers that DHCP requests should be relayed to

**Comment by maximcoder** [comment]
I have the fix , but I'm new to the github and dont know how to do upload the change for review.
Thx

**Comment by ipsoftar** [comment]
You would have to create a pull request to submit the change to be merged into the main repo

**Comment by maximcoder** [comment]
I did,# Pull request 41 opened 3 days ago by maximcoder
