### ISSUE TITLE
Request firmware version in getdevicedetail()

### ISSUE THREAD

**Issue by craigbruenderman** [meraki/dashboard-api-python#6]
I don't see any methods returning device firmware version. This would be very useful to me. Can someone point me in the right direction to get at that data?

**Comment by shiyuechengineer** [comment]
Hi Craig, there aren't any API calls for this feature yet, so in the meantime, the best way to do obtain this information is on the _Organization > Firmware upgrades_ page, which lists the firmware version for every network and more.
