### ISSUE TITLE
sdk unhandled exception on request timeout

### ISSUE THREAD

**Issue by ozgurakcali** [meraki/dashboard-api-python#61]
The following unhandled exception is raised when a request timeout occurs (and all retires are done):

**UnboundLocalError: local variable 'response' referenced before assignment**

This happens on [this](https://github.com/meraki/dashboard-api-python/blob/e29586fe3c48e3dc3278da747b73649a2d7d7d53/meraki/rest_session.py#L81) line on rest_session.py file

**Comment by shiyuechengineer** [comment]
Thank you for your feedback, Ozgur! That line has been fixed in the newest release 0.80.0.
