### ISSUE TITLE
request: output logging just to console

### ISSUE THREAD

**Issue by risteon1** [meraki/dashboard-api-python#63]
In next release, can we have the ability to log only to console without having to write a log file also? Thanks!

**Comment by shiyuechengineer** [comment]
Sure, I'll add an option for that!

**Comment by merakite** [comment]
I was also looking for this, thanks @shiyuechengineer !

**Comment by shawnhu2020** [comment]
I was also looking for this, thanks @shiyuechengineer !

**Comment by shiyuechengineer** [comment]
This feature has now been added. Thank you for the suggestion guys!
