### ISSUE TITLE
Missing REST endpoints

### ISSUE THREAD

**Issue by Kurtas** [meraki/dashboard-api-python#64]
Hello,

we have a problem with Cisco Meraki REST API (https://developer.cisco.com/meraki/api/#/rest/)

It seems that there doesn't exist REST endpoints for getting such basic information like ARP, MAC, routing tables etc. We can see that information in the Meraki app where those data received through the CometD web messaging service.

Is there any way how we can get those data in some kind of public API?

**Comment by shiyuechengineer** [comment]
I'm not really sure what you mean by "We can see that information in the Meraki app where those data received through the CometD web messaging service". Can you elaborate on that further please?

**Comment by Kurtas** [comment]
We supposed that Dashboard App will be fully built using REST API endpoints, so we tried to investigate (using chromer developer tools) how are data fetched for the ARP table in Dashboard App and we found out that the data are received from CometD messaging service.

We still don't know how to get for example ARP table through a REST API endpoint, we're blind or it doesn't exist.

**Comment by shiyuechengineer** [comment]
ARP table functionality does not exist today via an API endpoint. While new features are being built API first, there are legacy features like this one that do not have a corresponding API call.
