### ISSUE TITLE
New Python SDK Documentation not updated

### ISSUE THREAD

**Issue by LongBeachHXC** [meraki/dashboard-api-python#67]
Hey @shiyuechengineer it appears that the documentation located at 

https://developer.cisco.com/meraki/ 

was updated with the new SDK information but the documentation located at:

https://developer.cisco.com/meraki/api/#/python/getting-started

is still referencing the old SDK.

Just wanted to bring to your attention.

**Comment by shiyuechengineer** [comment]
This will finally be fixed in the next few days. Thanks for your patience... documentation is not easy. 😄
