### ISSUE TITLE
Can't set perclientbandwidthlimit

### ISSUE THREAD

**Issue by bradmorg** [meraki/dashboard-api-python#69]
If I do anything for as a none 0 value for 'perClientBandwidthLimitDown' or 'perClientBandwidthLimitUp' i get the error 'Download bandwidth is too small (minimum: 20Kbps)'.

The value that I am sending, 10240, should work, and does work if I manually set it through the dashboard.

dashboard.ssids.updateNetworkSsid(networkid, ssidnum, **ssid)
 Bad Request, {'errors': ['Download bandwidth is too small (minimum: 20Kbps)']}]
[[{'adminSplashUrl': None,
   'authMode': 'psk',
   'bandSelection': 'Dual band operation',
   'enabled': True,
   'encryptionMode': 'wpa',
   'ipAssignmentMode': 'NAT mode',
   'minBitrate': 11,
   'name': 'My Home Lab',
   'number': 0,
   'perClientBandwidthLimitDown': 10240,
   'perClientBandwidthLimitUp': 10240,
   'psk': 'SonderGuest',
   'splashPage': 'Click-through splash page',
   'splashTimeout': '1440 minutes',
   'ssidAdminAccessible': False,
   'walledGardenEnabled': False,
   'wpaEncryptionMode': 'WPA2 only'},
  SSIDs, updateNetworkSsid - 400 Bad Request, {'errors': ['Download bandwidth is too small (minimum: 20Kbps)']},
  SSIDs, updateNetworkSsid - 400 Bad Request, {'errors': ['Download bandwidth is too small (minimum: 20Kbps)']}]]

**Comment by shiyuechengineer** [comment]
It seems like dashboard requires you to enter a value of at least 20 (Kbps) as well. The value you are sending via the API call is also in the same units, so if you try a number say 20 or 500, you should see that change reflected.

**Comment by bradmorg** [comment]
> It seems like dashboard requires you to enter a value of at least 20 (Kbps) as well. The value you are sending via the API call is also in the same units, so if you try a number say 20 or 500, you should see that change reflected.

Hello,

It doesn't seem to matter what value I put. If I use anything other then 0 it returns the error:  400 Bad Request, {'errors': ['Download bandwidth is too small (minimum: 20Kbps)']}

I tried 20 and 500 like you suggested.  I assume you would get the same result on your test system?

I actually think the problem is with the Meraki API itself and not the dashboard api python module.

**Comment by shiyuechengineer** [comment]
Correct, this issue isn't with the Python module. I was able to get this working in both Postman and Python earlier, so if you're still seeing this issue, please open a Support case to troubleshoot further.
