### ISSUE TITLE
newssid: SSID error

### ISSUE THREAD

**Issue by osiris123d** [meraki/dashboard-api-python#7]
Traceback (most recent call last):
  File "myNetworks.py", line 1, in <module>
    from meraki import meraki
  File "/root/dashboard-api-python/meraki.py", line 3267
    def updatessidobject(apikey, networkid, newssid: SSID, suppressprint=False):
                                                   ^
SyntaxError: invalid syntax

**Comment by grutz** [comment]
I'll submit a PR to fix but removing `: SSID` will at least get the code running.

```
diff --git a/meraki.py b/meraki.py
index c50b4cf..863fffc 100644
--- a/meraki.py
+++ b/meraki.py
@@ -3264,7 +3264,7 @@ def updatessid(apikey, networkid, ssidnum, name, enabled, authmode, encryptionmo

 # Update the attributes of an SSID
 # https://api.meraki.com/api_docs#update-the-attributes-of-an-ssid
-def updatessidobject(apikey, networkid, newssid: SSID, suppressprint=False):
+def updatessidobject(apikey, networkid, newssid, suppressprint=False):
     '''

     Args:
```

**Comment by osiris123d** [comment]
:thumbsup:

**Comment by shiyuechengineer** [comment]
which version Python are you guys running here?
