### ISSUE TITLE
dashboard-api-python issue

### ISSUE THREAD

**Issue by hansonchi** [meraki/dashboard-api-python#70]
Hi
    I am try copy your code to run , I copied and pasted to Pycharm , when I run it , I have get my organization code and get error message as below:

Analyzing organization other license.com:
  - iterating through 1 networks in organization 66934XXXXXXXXXXXXXX
Finding clients in network API-Lab (1 of 1)
Traceback (most recent call last):
  File "/Users/kitoorunoboru/PycharmProjects/dashboard-api-python-master/test.py", line 96, in <module>
    main()
  File "/Users/kitoorunoboru/PycharmProjects/dashboard-api-python-master/test.py", line 77, in main
    field_names = list(field_names)
UnboundLocalError: local variable 'field_names' referenced before assignment

can you help me ? thanks !

**Comment by shiyuechengineer** [comment]
Can you add a "print(clients)" line underneath the "if clients:" block, and re-run please? Curious why clients are returned but they do not have keys.

**Comment by hansonchi** [comment]
I have add command and rerun , error message is same as before , I have take screen shot as this link [https://www.dropbox.com/s/u45hjfr08k1bacn/%E6%88%AA%E5%9C%96%202020-03-05%20%E4%B8%8A%E5%8D%888.59.18.png?dl=0](url) , thank you !

**Comment by shiyuechengineer** [comment]
It seems like you only have one network in this org but there are no clients at all in that single network. Is that correct? Which is why the shortcut here to use CSV field names from the dict/object's keys doesn't work since no clients are returned at all.

**Comment by hansonchi** [comment]
thank you ! is my org issue , I'll use another org test .
