### ISSUE TITLE
Bug since 0.90

### ISSUE THREAD

**Issue by marianne-butaye** [meraki/dashboard-api-python#72]
Hello,

I tried your new release which should have fixed #68, but I think the SDK is broken now... ;)

The thing is, I receive the correct logs from your application, such as :
```python
09/03/2020 16:03:12 [ERROR] rest_session::request::160 - Networks, createOrganizationNetwork - 400 Bad Request, {'errors': ['Name has already been taken']}
```
The problem is the fact that the data returned by the calls is always `None None, None` (printed in str format as `Networks, createOrganizationNetwork - None None, None`)
For example, for the same call above I get this __dict__ of values on the error:
```python
09/03/2020 16:03:12 [WARNING] decorators::wrapper::74 - {'response': <Response [400]>, 'tag': 'Networks', 'operation': 'createOrganizationNetwork', 'status': None, 'reason': None, 'message': None}
```

**Comment by shiyuechengineer** [comment]
Thanks for reporting this issue! It should be fixed now with this latest update; can you check please?

**Comment by marianne-butaye** [comment]
Hi again, 

I checked and now the SDK is repaired, but I found another bug, related as before to the root cause of #68, which is an unknown error thrown pretty often (30% of the time maybe or a bit below but pretty often still)(maybe a Timeout from Meraki ? I'm not sure, I never got as far as to get an error from your SDK about it yet, as there are still some bugs in between).

Below is the error message:

```python
File "./app/lib/meraki_api.py", line 210, in _create_network
dev_1         |     organization_id, name=self.site.name, tags=tags, type="appliance", timeZone=self.site.timezone)
dev_1         |   File "/usr/local/lib/python3.7/site-packages/meraki/api/networks.py", line 279, in createOrganizationNetwork
dev_1         |     return self._session.post(metadata, resource, payload)
dev_1         |   File "/usr/local/lib/python3.7/site-packages/meraki/rest_session.py", line 227, in post
dev_1         |     response = self.request(metadata, 'POST', url, json=json)
dev_1         |   File "/usr/local/lib/python3.7/site-packages/meraki/rest_session.py", line 90, in request
dev_1         |     raise APIError(metadata, response)
dev_1         |   File "/usr/local/lib/python3.7/site-packages/meraki/exceptions.py", line 17, in __init__
dev_1         |     self.status = self.response.status_code if self.response.status_code else None
dev_1         | AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by shiyuechengineer** [comment]
OK this should be fixed too now, with a check added for NoneType in APIError exception.

**Comment by marianne-butaye** [comment]
I confirm this works now ;)
