### ISSUE TITLE
aio exception problem

### ISSUE THREAD

**Issue by TribesTom** [meraki/dashboard-api-python#73]
Hello,

I think there is a problem with the exception AsyncAPIError(Exception):

When an exception occur, the exception try to call self.response.json()
Or it should be awaited.

The exception : 

`PS C:\Users\ttr\Documents\dev\meraki-winmonitor> python.exe .\win-meraki-provide.py -c .\config.ini -m Y
C:\Users\ttr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\meraki\exceptions.py:37: RuntimeWarning: coroutine 'ClientResponse.json' was never awaited
  self.message = self.response.json() if self.response.json() else None
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Test 1 : ******
.\win-meraki-provide.py:311: RuntimeWarning: coroutine 'ClientResponse.json' was never awaited
  print('Test 1 : {}'.format(org['name']))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

The code used : 

`    try:

        results = await aiomeraki.organizations.getOrganizationInventory(org["id"],includeLicenseInfo ='True')

    except:

        print('Test 1 : {}'.format(org['name']))`

It happen if the organisation is not licensed by device.

Thanks

**Comment by TribesTom** [comment]
Hello,

Do you need more info regarding this bug ?

Have a nice day.

**Comment by shiyuechengineer** [comment]
Since the async module was added by @coreGreenberet, I'll let him comment.

Just curious: what is the rationale behind using async here?

**Comment by coreGreenberet** [comment]
> 
> 
> Hello,
> 
> Do you need more info regarding this bug ?
> 
> Have a nice day.

No thanks, I can see what the problem here is. I think I can fix it tomorrow.

**Comment by TribesTom** [comment]
Hello,

Thanks for your response.

My project has two purpose : 

Sync info from Meraki to a local db
Monitor device status every 5 minutes and integrate it with local tool.

The number of organization and device may increase a lot in future.

With async I can ensure that the request are done fast as I have read that request rate is limited by organization.

I have done it already with aiohttp directly but I think it's more future proof to go with an official lib.

Have a nice day

**Comment by TribesTom** [comment]
Hello, thanks for the fix.
