### ISSUE TITLE
Mysterious error

### ISSUE THREAD

**Issue by marianne-butaye** [meraki/dashboard-api-python#74]
Hello,

Following the debugging of the SDK from issues #68 & #72, I still get my mysterious error happening at random on any type of call made to Meraki, quite frequently.

Now, with your fix I get this sort of error: `Organizations, getOrganizations - None None, None`. 
Do you know the origin of this error (timeout from Meraki, network problem, ...)? 
Would you be able to send back a true error for it? I mean with an error message/code/etc., because None does not tell us what is the origin or why it happened in the first place. 
I myself do not know where it comes from. 

To resolve it without interrupting the user, I usually do a `sleep(0.5)` and then retry the call.
For each of our discussions in previous issues, I usually deploy a new network with devices etc. to test the error. It does not happen every time, but I usually only need a few calls (1-5) to get it again.

**Comment by shiyuechengineer** [comment]
Can you include your log file please or email to me? shiychen [at] cisco [dot] com

**Comment by shiyuechengineer** [comment]
Any update here please to provide additional data, @marianne-butaye?

**Comment by marianne-butaye** [comment]
Hi @shiyuechengineer,
I won't be able to work on this project this week. I will be able to provide additional data from next week if I can reproduce it in my current working environment - at home (which is different from usual because of Coronavirus containment measures). Can this issue be put in a 'wait' or 'on the side' state for the moment ?

**Comment by shiyuechengineer** [comment]
Of course! Please be safe there.
