### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by zabrewer** [meraki/dashboard-api-python#81]
@shiyuechengineer, running into a minor issue that I think we fixed in the legacy meraki.py library.  Or maybe I re-wrote it for a project, I can't remember.

Basically if someone mistypes an API key you get a series of errors but the most relevant is from the requests library.  Because the dashboard still returns a web page you get a 200 HTTP response but invalid JSON from requests response.json() (basically the dashboard response is HTML but the requests library expects json)

**File "/site-packages/meraki/rest_session.py", line 126, in request response.json()
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)**

Can we trap for this error? I trap for it often to give a custom user message.  I see it when people are using my tools based on your library but either use the wrong API key or mistype it.

If you can think of a work around without monkey patching (which I don't want to do), please let me know.  It's easy to re-create, just use any invalid API key.

**Comment by zabrewer** [comment]
Also, that error should be a trapped by either `except ValueError:` or more specifically `json.decoder.JSONDecodeError: ` but neither seem to work - still testing.  I think it has something to do with dependencies in imported modules and "During handling of the above exception, another exception occurred:" multiple errors.

**Comment by shiyuechengineer** [comment]
Hey Zach, that JSON error should be trapped under [this block](https://github.com/meraki/dashboard-api-python/blob/master/meraki/rest_session.py#L125) if it was a 200 response with invalid JSON returned. However, if the original issue was an invalid API key, then the response in V0 should be a 404 and in V1 401 with message "Invalid API key".

**Comment by shiyuechengineer** [comment]
Zach, anything else you need here before closing this issue? Thanks.

**Comment by zabrewer** [comment]
Shyue, Sorry I missed this.  The json.decoder.JSONDecodeError: doesn't catch the exception b/c the API returns HTTP content when an API key is bad.
