### ISSUE TITLE
AP status?

### ISSUE THREAD

**Issue by ajwillo** [meraki/dashboard-api-python#84]
Hello,

Is there an access point status query in the module anywhere? i.e a query that shows, up, repeater, down? I can't seem to find if it does exist? or could this be a feature request?

Thanks
Alex.

**Comment by shiyuechengineer** [comment]
Hi @ajwillo, there's the heavily-used organization-wide [GET endpoint](https://developer.cisco.com/docs/meraki-api-v1/#!get-organization-devices-statuses) to retrieve the online/alerting/offline status of every device (including wireless APs) in the org. Also, just released last week is a new network-scoped endpoint that shows the mesh performance of repeaters: the documentation will be added with this [new page](https://developer.cisco.com/docs/meraki-api-v1/#!get-network-wireless-mesh-statuses) shortly, but in the meantime, you can see it [here](https://api.meraki.com/api_docs/v1#list-wireless-mesh-statuses-for-repeaters) on the legacy docs.
