### ISSUE TITLE
Enhanced User-Agent

### ISSUE THREAD

**Issue by nerdguru** [meraki/dashboard-api-python#86]
Per the email exchange we had internally, the idea here is to enhance the information placed in the User-Agent HTTP Request header to be more like what pip does as can be seen here:

https://github.com/pypa/pip/blob/master/src/pip/_internal/network/session.py

In addition to the SDK version string, pip appends a URL encoded JSON string that includes things like OS version of the caller and Python version.  It would be nice to also have a field in that string that partners could set that would identify API calls made by them.  I just forked the repo and am working on a patch for this exact scenario.

**Comment by shiyuechengineer** [comment]
Thanks for the contributions, Pete!
