### ISSUE TITLE
Logs are printing and log files generated without setting logging

### ISSUE THREAD

**Issue by jvanderaa** [meraki/dashboard-api-python#87]
This looks to be newer behavior at the moment. But logs are now being printed to the output, and also a file is being created in the project directory without having logs setup. I see creating files and printing output to the screen as something that the application developer should choose to do, not the SDK.

**Comment by shiyuechengineer** [comment]
It's the default behavior for this library for a while now, and you can disable logging completely if you like with the option provided in the latest v0/v1 versions. The way we see it, having an output log automatically created is a helpful convenience, just like many of the other options this library/SDK provides
