### ISSUE TITLE
meraki.getgrouppolicies()  groupPolicyId is a string. in meraki.getclientpolicy() its a int

### ISSUE THREAD

**Issue by llathrop** [meraki/dashboard-api-python#89]
meraki.getgrouppolicies()  "groupPolicyId" is a string. In meraki.getclientpolicy() its an int. I believe these should be, and were at some point previously, the same. Workaround is to cast one to the type of the other.

I use getgrouppolicies() to collect the name and ID of the policies and allow the user to select the interesting one, and then later getclientpolicy() to grab the clients with a certain policy, and move them to a different policy.

an example:

meraki_group_policies=meraki.getgrouppolicies(meraki_keys['apikey'],meraki_keys['networkid'], suppressprint=True)
    policy_IDs={}
    for policy in meraki_group_policies:
**#notice the cast to int here as the workaround**
        policy_IDs[int(policy['groupPolicyId'])]=policy['name']

 meraki_clients=meraki.getclients(meraki_keys['apikey'],meraki_keys['device_serial'], suppressprint=True)
 for client in meraki_clients:
        client_policy=meraki.getclientpolicy(meraki_keys['apikey'], clientmac=client['mac'], networkid=meraki_keys['networkid'], suppressprint=True)
        if  client_policy:
            if 'groupPolicyId' in client_policy.keys():
**# the below test fails as they are different types**
                if client_policy['groupPolicyId'] in policy_IDs and client_policy['groupPolicyId'] in policy_ID_selected :
                      print("found the selected policy")

**Comment by shiyuechengineer** [comment]
Thanks for flagging this Luke. We'll get this standardized to a string (since it's a label really that doesn't have any numeric meaning) for the `getNetworkClientPolicy` and `updateNetworkClientPolicy` operations in v1.

**Comment by shiyuechengineer** [comment]
This issue has now been fixed so that the `groupPolicyId` is returned as a string. Thanks for reporting, Luke!
