### ISSUE TITLE
moveMapMarker Not Working When Updating A Device

### ISSUE THREAD

**Issue by neveragain2003** [meraki/dashboard-api-python#95]
When I call the updateNetworkDevice function from devices and an address is specified and moveMapMarker is set to True, the map marker does not move in the dashboard.  I can also specify the lat and lng when calling the same function, excluding the moveMapMarker parameter, and the map marker will still not move in the dashboard.  If I login to the dashboard and open the address properties of the device and click save without modifying the address, it will move it to where it's supposed to be.

**Comment by shiyuechengineer** [comment]
I just tested and it was successful for me. It would be helpful to troubleshoot your situation if you included information like the version of the library you're using, your source code, and also the logging data as evidence of whether you are getting 2XX responses. Here's what works for me on the latest beta version 1.0.0b8:

```python
import meraki
m = meraki.DashboardAPI()
m.devices.updateDevice(serial, address='500 Terry A Francois Blvd, San Francisco, CA 94158', moveMapMarker=True)
```

**Comment by shiyuechengineer** [comment]
Here's the code with the same result (200 OK, address updated and map marker moved successfully) on version 0.110.3.

```python
import meraki
m = meraki.DashboardAPI()
m.devices.updateNetworkDevice(network_id, serial, address='500 Terry A Francois Blvd, San Francisco, CA 94158', moveMapMarker=True)
```

**Comment by neveragain2003** [comment]
Tried the following on version 0.90.2:
import meraki
apiKey = 'APIKEY'
dashboard = meraki.DashboardAPI(api_key=apiKey)
kwargs = {
            'address': '6100 Tower Circle, Franklin, TN 37067',
            'moveMapMarker ': True
        }
dashboard.devices.updateNetworkDevice(networkID, serial, **kwargs)

I get a 200 response and the address is changed but the marker is not moved in the dashboard.

When I do it your way and remove the **kwargs and put the parms inline with the function call, it works.  Any advice as to why it will take the address in the kwargs but not the moveMapMarker?

**Comment by shiyuechengineer** [comment]
Thanks for providing that information since it's exactly what is needed to troubleshoot. The reason why it doesn't work is because of the extra trailing space in the `'moveMapMarker '` key. Remove that, and you will be able to make the change successfully.

**Comment by neveragain2003** [comment]
Thank you for the information.  I did not notice the extra space.

**Comment by shiyuechengineer** [comment]
No problem and due to this issue you've reported, we'll make a change to future versions so that errant spaces like this will be fixed automatically, basically changing `payload = {k: v for (k, v) in kwargs.items() if k in body_params}` to `payload = {k.strip(): v for (k, v) in kwargs.items() if k.strip() in body_params}`.

**Comment by neveragain2003** [comment]
I am curious why you allow values that are not valid and not have it error out?  I just ran into a similar issue where I misspelled timeZone.  It didn't throw an error and it took me a minute to find the mistake.

**Comment by shiyuechengineer** [comment]
You can only do so much user error checking... if you try to make the API call separately of the Python library, you'll see you can include random attributes/objects to the request body, and it wouldn't return an error either.

**Comment by shiyuechengineer** [comment]
Hey @neveragain2003, thinking about this more, if we were to check for invalid input parameters like `moveMapMarker ` (with a space) or `timezone` (without capitalizing Z), what would you like to see happen? For example, a warning message that gets displayed to notify you about the typo (but still proceeding to make the call), or an exception where that call is not made entirely at all?
