### ISSUE TITLE
String limit for destCidr

### ISSUE THREAD

**Issue by vitaliymsms** [meraki/dashboard-api-python#96]
I'm sorry to ask you this here, but only you can help me. What's the "destCidr" limit? How many IP addresses can there be in one rule (or string length limit) ? I'm working on automation right now and I want to have one Black list for each brunch.

Thank you for your job and for API.

**Comment by shiyuechengineer** [comment]
I suppose you should thank Cisco Meraki for my job. 😄 

Which API endpoint are you working with exactly? Have you tried testing, both with the API call and in dashboard UI?

**Comment by liangjian1999** [comment]
Another option is to submit a support case to Meraki. But of course Shiyue will offer the best in class support directly.

**Comment by vitaliymsms** [comment]
> Another option is to submit a support case to Meraki. But of course Shiyue will offer the best in class support directly.

The problem is, I've already opened a case to Meraki support (Case 04777604). The official answer is we don't know and can't give you an answer.

**Comment by vitaliymsms** [comment]
> I suppose you should thank Cisco Meraki for my job. 😄
> 
> Which API endpoint are you working with exactly? Have you tried testing, both with the API call and in dashboard UI?

I'm adding a firewall rule using the following query. (PUT/networks/{networkId}/appliance/firewall/l3FirewallRules)
Everything works well, but my question is - what is the limit on the number of IP addresses in one rule. (or there is a limit on the line (destCidr) size) 
For example, the Windows Firewall has a limit of 1000 entries (addresses or subnets) per rule. 
Thank you for your help. Waiting for your response.

**Comment by shiyuechengineer** [comment]
While there are certainly limits to what the appliance can handle in terms of processing, and in addition, limits to what you can set in the UI and via API in terms of maximum payload (as nothing is infinite), you'll find that adding more IP addresses & rules beyond a certain point will take much longer to process (both in UI and via API).

That being said, 1000 addresses per rule is something I've seen only occasionally on customers' networks, and while it might not be the best way to design security, having a few of these "mega" rules isn't out of possibility.

For example: I just ran a quick, successful with the following snippet to create a rule with 256^2 = 65536 IP addresses for the `destCidr` field:
```python
import meraki
dashboard = meraki.DashboardAPI(single_request_timeout=300)

addresses = ''
for x in range(256):
    for y in range(256):
        addresses += f'10.0.{x}.{y},'
addresses = addresses[:-1]

rules = [
    {
        'policy': 'allow',
        'protocol': 'any',
        'destPort': 'any',
        'destCidr': addresses,
        'srcPort': 'any',
        'srcCidr': 'any',
    }
]
network_id = 'L_629378047925041309'
rules = dashboard.appliance.updateNetworkApplianceFirewallL3FirewallRules(
    network_id,
    rules=rules,
)
addresses = rules['rules'][0]['destCidr']
print(len(addresses.split(',')))
```
