### ISSUE TITLE
v1 api - security_events missing?

### ISSUE THREAD

**Issue by austinnichols101** [meraki/dashboard-api-python#97]
This code fails in 1.0.0b8:
```
dashboard.security_events.getOrganizationSecurityEvents(organizationId=organization_id)
```
with the following error
```
AttributeError: 'DashboardAPI' object has no attribute 'security_events'
```

**Comment by shiyuechengineer** [comment]
That's expected, as the functions have changed with v1 of the Python library just like other [breaking changes](https://developer.cisco.com/meraki/api-v1/#!introduction/whats-new-in-v1) when moving from v0 to v1.  In this case, the scope has changed to `appliance` so you'll need to use the v1 [library's function](https://developer.cisco.com/meraki/api-v1/#!get-organization-appliance-security-events), `dashboard.appliance.getOrganizationApplianceSecurityEvents()` instead.
