### ISSUE TITLE
dashboard.intrusion_settings.getNetworkSecurityIntrusionSettings()

### ISSUE THREAD

**Issue by craigbruenderman** [meraki/dashboard-api-python#98]
This seems to blow up on vMX devices.

```
meraki.exceptions.APIError: Intrusion settings, getNetworkSecurityIntrusionSettings - 400 Bad Request, {'errors': ['Intrusion detection is not supported by this network']}
```

**Comment by shiyuechengineer** [comment]
That's expected, as vMX does not support this IPS/IDS feature.

**Comment by craigbruenderman** [comment]
Understood, but it would be nice if there was logic around it. Right now I have to handle the exception since I'm not aware of a way to test for the presence of a VMX.

**Comment by shiyuechengineer** [comment]
There's not much that can be done with the individual call, but what can be done is check the devices of a network (or org) to determine which networks have vMX100, but then again, this call will still fail for orgs not using MX Advanced Security licensing.
