### ISSUE TITLE
How to get vlans in 0.110.x ?

### ISSUE THREAD

**Issue by ksquarekumar** [meraki/dashboard-api-python#99]
Hi,

I am trying to get information on VLANS on an MX Network.

The Cisco - Meraki developer guides state that this is possible:

https://developer.cisco.com/meraki/api/#!get-network-vlans
https://developer.cisco.com/meraki/api/#!get-network-vlans

but i am not able to find any up to date information on how to do the same with the dashboard-api.

this is what's there on the developer portal
```python
dashboard.vlans.getNetworkVlans(network_id)
```
but this results in an error, like so:
```console
AttributeError: 'DashboardAPI' object has no attribute 'vlan'
```

I also tried to find if there is a GetVLAN attribute somewhere in `dashboard.network` but so far i couldn't find one, can the dev team help with this ?

**Comment by shiyuechengineer** [comment]
Hi Krishna, you need to use `dashboard.vlans.getNetworkVlans` (with an `s` at the end there), and not doing so will result in that `AttributeError` that you're seeing.

**Comment by ksquarekumar** [comment]
> 
> 
> Hi Krishna, you need to use `dashboard.vlans.getNetworkVlans` (with an `s` at the end there), and not doing so will result in that `AttributeError` that you're seeing.

@shiyuechengineer, are you sure ?
`vlans` gets me the same error as `vlan`, it is also not a valid attribute (or atleast in my case).

```python
import meraki
dashboard = meraki.DashboardAPI(api_key=MERAKI_DASHBOARD_API_KEY)
```

this is the output from `dir(dashboard)`

```console
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_log_file',
 '_logger',
 '_session',
 'appliance',
 'camera',
 'cellulargateway',
 'devices',
 'insight',
 'networks',
 'organizations',
 'sm',
 'switch',
 'wireless']
```

as you can see there is no `vlans` attribute inside `dashboard`

with a little but of digging around, i was able to find all the `VLan` related attributes, but they seem to be inside `dashboard.appliance` and not `dashboard` like you stated.

```python
dir_eval = lambda x, bk:[x for x in dir(eval('.'.join([*x]))) if bk not in x]

top = 'dashboard'
pattern = 'vlan'
block = '_'

for attrib in dir_eval([top],block):
    attribs = dir_eval([top,attrib],block)
    for att in attribs:
        if pattern in att.lower():
            print(f'{top}.{attrib}.{att}')
```

Here is the output from the above code
```output
dashboard.appliance.createNetworkApplianceVlan
dashboard.appliance.deleteNetworkApplianceVlan
dashboard.appliance.getNetworkApplianceVlan
dashboard.appliance.getNetworkApplianceVlans
dashboard.appliance.getNetworkApplianceVlansSettings
dashboard.appliance.updateNetworkApplianceVlan
dashboard.appliance.updateNetworkApplianceVlansSettings
```

can you please let me know if this is the intended behavior or not ?

**Comment by shiyuechengineer** [comment]
You have the v1 library installed but referenced v0 in your documentation link above. For v1 ([documentation](https://developer.cisco.com/meraki/api-v1/#!get-network-appliance-vlans)), which looks like the version of Python library you have installed, then use `dashboard.appliance.getNetworkApplianceVlans`, as opposed to the v0 ([documentation](https://developer.cisco.com/meraki/api/#!get-network-vlans))function I have above.

**Comment by ksquarekumar** [comment]
yes i see that the difference is between v0 and v1 version of docs.
thanks a lot!
